[package]
name = "toa-cli"
version = "0.1.0"
edition = "2024"

[features]

[dependencies]
toa = { path = "../toa", features = ["lz4", "zstd"] }
memmap2 = { version = "0.9.9", default-features = false }
rand = { version = "0.8.0" }
toa-blob = { path = "../toa-blob", features = ["std"] }
toa-hash = { path = "../toa-hash" }
