[package]
name = "toa-blob-compress"
version.workspace = true
edition.workspace = true

[features]
lz4 = ["dep:lz4_flex"]
zstd = ["dep:zstd-safe"]

[dependencies]
bytemuck.workspace = true
lz4_flex = { workspace = true, optional = true }
nora_endian.workspace = true
toa-blob-store.workspace = true
zstd-safe = { workspace = true, optional = true }

[dev-dependencies]
toa-blob.workspace = true
