[package]
name = "toa"
version.workspace = true
edition.workspace = true

[features]
lz4 = ["toa-blob-compress/lz4"]
zstd = ["toa-blob-compress/zstd"]
accel-sled = ["dep:sled"]

[dependencies]
arrayvec.workspace = true
bytemuck.workspace = true
nora_endian.workspace = true
sled = { workspace = true, optional = true }
toa-blob-compress.workspace = true
toa-blob-store.workspace = true
toa-blob.workspace = true
toa-hash.workspace = true
